# Generated by Django 5.2 on 2025-06-05 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0002_initial'),
        ('store', '0003_product_is_popular_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypc',
            options={'verbose_name': 'Категория ПК', 'verbose_name_plural': 'Категории ПК'},
        ),
        migrations.AlterModelOptions(
            name='compatibilityrule',
            options={'verbose_name': 'Правило совместимости', 'verbose_name_plural': 'Правила совместимости'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['price'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='pcbuild',
            options={'verbose_name': 'Сборка ПК', 'verbose_name_plural': 'Сборки ПК'},
        ),
        migrations.AlterModelOptions(
            name='pcbuildcomponent',
            options={'verbose_name': 'Компонент сборки', 'verbose_name_plural': 'Компоненты сборки'},
        ),
        migrations.AlterModelOptions(
            name='savedpcbuild',
            options={'verbose_name': 'Сохраненная сборка', 'verbose_name_plural': 'Сохраненные сборки'},
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_1', to='store.category', verbose_name='Категория 1'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='category2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_2', to='store.category', verbose_name='Категория 2'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='error_message',
            field=models.CharField(max_length=255, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='operator',
            field=models.CharField(choices=[('=', 'Равно'), ('!=', 'Не равно'), ('<', 'Меньше'), ('<=', 'Меньше или равно'), ('>', 'Больше'), ('>=', 'Больше или равно')], max_length=2, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='spec1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_1', to='store.specification', verbose_name='Характеристика 1'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='spec2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_2', to='store.specification', verbose_name='Характеристика 2'),
        ),
    ]
