# Generated by Django 5.2 on 2025-06-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_popular_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
    ]
