# Generated by Django 5.2 on 2025-06-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('topic', models.CharField(choices=[('general', 'Общий вопрос'), ('order', 'Вопрос по заказу'), ('delivery', 'Вопрос по доставке'), ('return', 'Вопрос по возврату')], default='general', max_length=20, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('response', models.TextField(blank=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
                'ordering': ['-created_at'],
            },
        ),
    ]
